---
name: dashmachine
version: dev.1
slug: dash1
description: Example add-on by Community Home Assistant Add-ons
url: https://github.com/tj31moll/dashmachine
codenotary: codenotary@frenck.dev
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - config:rw
  - ssl
ports:
  5666/tcp: 5666
options:
  log_level: info
  seconds_between_quotes: 5
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  seconds_between_quotes: int(1,120)
